services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: kpi_nexus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - kpi-network

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend  # New backend stage
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=kpi_nexus
      - DB_PORT=5432
      - JWT_SECRET=your-secret-key-change-in-production
    depends_on:
      - postgres
    networks:
      - kpi-network

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development  # Development stage for local dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - kpi-network

volumes:
  postgres_data:

networks:
  kpi-network:
    driver: bridge