services:
  - type: web
    name: kpi-nexus-platform
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: kpi-nexus-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: EMAIL_SERVICE
        value: gmail
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false

databases:
  - name: kpi-nexus-db
    databaseName: kpi_nexus
    user: kpi_user